version: 0.2

environment_variables:
    plaintext:
        "INPUT_FILE": "sam.yml"
        "S3_BUCKET": "ttulka-codepipelinebucket"

phases:
  #install:
    #commands:
      #- command
  #pre_build:
    #commands:
      #- command
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Packaging started on `date`
      - aws cloudformation package --template-file $INPUT_FILE --s3-bucket $S3_BUCKET --output-template-file template.yml

artifacts:
  type: zip
  files:
    - template.yml
    - dev.json