version: 0.2

phases:
  #install:
    #commands:
      #- command
  #pre_build:
    #commands:
      #- command
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Packaging started on `date`
      - aws cloudformation package --template-file sam.yml --s3-bucket talisker-codepipelinebucket --output-template-file template.yml

artifacts:
  type: zip
  files:
    - template.yml