AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda functions logs uploaded files from S3

Parameters:
    BucketName:
        Description: "S3 bucket name"
        Type: "String"

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

  UploadEventLogger:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: UploadEventLogger
      Handler: cz.net21.ttulka.cloud.server.aws.lambda.UploadEventLogger
      CodeUri: ./target/UploadEventLogger-1.0.0-SNAPSHOT.jar
      Runtime: java8
      MemorySize: 256
      Timeout: 30
      Policies:
      - Version: 2012-10-17
        Statement:
          - Resource: !Sub "arn:aws:s3:::${BucketName}/*"
            Action: s3:GetObject*
            Effect: Allow
          - Resource: arn:aws:logs:*
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Effect: Allow
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref Bucket
            Events: s3:ObjectCreated:*