swagger: "2.0"
info:
  version: "2018-03-20T13:41:34Z"
  title: "mp-datalake-upload"
basePath: /datalake
schemes:
  - https
paths:
  /:
    post:
      description: "Upload package"
      parameters:
        - name: packageId
          in: path
          type: string
          description: "The package ID"
          required: true
        - in: body
          name: "Upload request"
          schema:
            type: object
            required:
              - type
              - contentType
            properties:
              type:
                type: string
              contentType:
                type: string
              tags:
                type: array
                items:
                  $ref: '#/definitions/Tag'
      responses:
        200:
          description: "Package to upload"
          schema:
            type: object
            properties:
              packageId:
                type: string
                description: "Package ID"
              uploadUrl:
                type: string
                description: "Upload URL"

definitions:
  Tag:
    type: object
    description: "Response tags, this field is not always set"
    properties:
      key:
        type: string
      value:
        type: string
