AWSTemplateFormatVersion: "2010-09-09"
Description: "DataLake CI/CD Pipeline - RC|QA|PROD Account."

Parameters:

  CIAccountId:
    Type: String
    Description: "ARN of the CI Account"
    AllowedPattern: "[0-9]+"
    ConstraintDescription: "Account ID is a number"
    Default: "456158573912"

  KMSKey:
    Type: String
    Description: "ARN of the KMS Key"

Resources:

  CrossAccountRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-cross-account-role"
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${CIAccountId}:root"
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CrossAccountPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:*
                  - codebuild:*
                  - s3:*
                  - sns:*
                  - iam:PassRole
                Resource: "*"
              - Effect: Allow
                Action: ["kms:*"]
                Resource: !Ref KMSKey

  CloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-cloudformation-role"
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [cloudformation.amazonaws.com]
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudFormationPolicy
          PolicyDocument:
            Statement:
              - Action: ["s3:*"]
                Resource: "*"
                Effect: Allow
              - Action: ["kms:Decrypt", "kms:Encrypt"]
                Resource: !Ref KMSKey
                Effect: Allow
              - Action: ["iam:GetRole", "iam:CreateRole", "iam:DeleteRole", "iam:AttachRolePolicy", "iam:DetachRolePolicy", "iam:DeleteRolePolicy", "iam:PutRolePolicy", "iam:PassRole"]
                Resource: !Sub "arn:aws:iam::${AWS::AccountId}:role/*"
                Effect: Allow
              - Action: ["iam:PassRole"]
                Resource: !Sub "arn:aws:iam::${AWS::AccountId}:role/*"
                Effect: Allow
              - Action: ["cloudformation:*"]
                Resource: !Sub "arn:aws:cloudformation:${AWS::Region}:aws:transform/*"
                Effect: Allow
              - Action: ["sns:*"]
                Resource: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:*"
                Effect: Allow
              - Action: ["dynamodb:*"]
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/*"
                Effect: Allow
              - Action: ["lambda:*"]
                Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:*"
                Effect: Allow
              - Action: ["es:*"]
                Resource: !Sub "arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/*"
                Effect: Allow
              - Action: ["kms:*"]
                Resource: "*"
                Effect: Allow
