version: 0.2

phases:
  install:
    commands:
      - echo Installing jq...
      - curl http://stedolan.github.io/jq/download/linux64/jq -o ~/jq
      - chmod a+x ~/jq

  pre_build:
    commands:
      - cat $CODEBUILD_SRC_DIR_DeployArtifactTest/test-output.json
      - UPLOAD_PACKAGE_LAMBDA=`cat $CODEBUILD_SRC_DIR_DeployArtifactTest/test-output.json | ~/jq -r '.UploadPackageLambdaArn'`
      - echo $UPLOAD_PACKAGE_LAMBDA
      - DOWNLOAD_PACKAGE_LAMBDA=`cat $CODEBUILD_SRC_DIR_DeployArtifactTest/test-output.json | ~/jq -r '.DownloadPackageLambdaArn'`
      - echo $DOWNLOAD_PACKAGE_LAMBDA
      - SEARCH_PACKAGE_LAMBDA=`cat $CODEBUILD_SRC_DIR_DeployArtifactTest/test-output.json | ~/jq -r '.SearchPackageLambdaArn'`
      - echo $SEARCH_PACKAGE_LAMBDA
      - PUBLISH_PACKAGE_LAMBDA=`cat $CODEBUILD_SRC_DIR_DeployArtifactTest/test-output.json | ~/jq -r '.PublishPackageLambdaArn'`
      - echo $PUBLISH_PACKAGE_LAMBDA
      - TAGGING_SERVICE_LAMBDA=`cat $CODEBUILD_SRC_DIR_DeployArtifactTest/test-output.json | ~/jq -r '.TaggingServiceLambdaArn'`
      - echo $TAGGING_SERVICE_LAMBDA

  build:
    commands:
      - cd it-tests
      - npm install
      - npm test
